### ISSUE TITLE
关于群id的

### ISSUE THREAD

**Issue by aermin** [aermin/vue-chat#1]
新建群的时候，不像新建用户那样有用户名作为独特唯一的标记，
那怎么办呢？

想到两种方案：

1.新增一个字段，用uuid的包生成uuid放进去 
[package/uuid](https://www.npmjs.com/package/uuid)

使用方法 ：

```js
const uuidv1 = require('uuid/v1');
uuidv1(); // ⇨ 'f64f2940-fae4-11e7-8c5f-ef356f279131'
```

2.在执行建群操作时返回自增id  
SELECT LAST_INSERT_ID()
这个没能搞定，没能简单搞定。。。

我选择了第一个方案，没在刚开始就注意到这个问题，现在要改不少地方。。😂吃下这一堑了

**Comment by snimstice** [comment]
加油 ToT
